# Generated by Django 6.0.3 on 2026-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('country', models.CharField()),
                ('batting_style', models.CharField()),
                ('bowling_style', models.CharField()),
                ('age', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
            ],
        ),
    ]
