# Generated by Django 6.0.3 on 2026-06-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('enroll', models.CharField()),
                ('dob', models.DateField()),
                ('projectTitle', models.CharField()),
            ],
        ),
    ]
