# Generated by Django 6.0.3 on 2026-06-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField()),
                ('dept_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('eno', models.IntegerField()),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coll.dep')),
            ],
        ),
    ]
