# Generated by Django 6.0.3 on 2026-06-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coll', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep',
            name='dept_name',
            field=models.CharField(null=True),
        ),
    ]
